
server:
  port: 8080

spring:
  datasource:
    katarina:
      driver-class-name: org.mariadb.jdbc.Driver
      jdbc-url: jdbc:mariadb://localhost:3306/katarina?serverTimezone=UTC&characterEncoding=UTF-8
      username: root
      password: 1234
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect