
riot:
  api-key: "RGAPI-cc2ed2de-c129-49de-a84c-02d0bccbdbf5"


logging:
  level:
    root: info

spring:
  datasource:
    matcher:
      driver-class-name: org.mariadb.jdbc.Driver
      jdbc-url: jdbc:mariadb://localhost:3306/matcher?serverTimezone=UTC&characterEncoding=UTF-8
      username: root
      password: 1234
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect