
riot:
  api-key: "RGAPI-f1498d86-90a8-45e8-adb1-86a11e86d329"

logging:
  level:
    root: info

spring:
  datasource:
    matcher:
      driver-class-name: org.mariadb.jdbc.Driver
      jdbc-url: jdbc:mariadb://localhost:3306/matcher?serverTimezone=UTC&characterEncoding=UTF-8
      username: root
      password: 1234

    statistics:
      driver-class-name: org.mariadb.jdbc.Driver
      jdbc-url: jdbc:mariadb://localhost:3306/statistics?serverTimezone=UTC&characterEncoding=UTF-8
      username: root
      password: 1234
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect