
riot:
  api-key: "RGAPI-b4c0285d-4bd9-4687-980e-72329148cf72"

logging:
  level:
    root: info

spring:
  datasource:
    matcher:
      driver-class-name: org.mariadb.jdbc.Driver
      jdbc-url: jdbc:mariadb://localhost:3306/matcher?serverTimezone=UTC&characterEncoding=UTF-8
      username: root
      password: 1234

    statistics:
      driver-class-name: org.mariadb.jdbc.Driver
      jdbc-url: jdbc:mariadb://localhost:3306/statistics?serverTimezone=UTC&characterEncoding=UTF-8
      username: root
      password: 1234
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect